config {
    type: "table",
    dependencies: ["farmland_boundaries"]
}

/*
The resolve function lets you reference a table or data source declaration in a SELECT statement like the ref function, 
but it doesn't add the reference as a dependency. 

This means that the object referenced using the resolve function does not affect the execution of the table that uses the resolve function.
*/
SELECT
  *
FROM
  ${resolve("farmland_boundaries")}

